location /extras/webremote {
#	rewrite ^([^.\?]*[^/(/ws)])$ $1/ permanent;
#	rewrite ^/extras/webremote$ / break;
#	rewrite ^/extras/webremote?(.*)$ ?$1 break;
#	rewrite ^/extras/webremote/(.*)$ /$1 break;
	proxy_pass http://192.168.178.38;
	include /etc/kvmd/nginx/loc-proxy.conf;
	include /etc/kvmd/nginx/loc-websocket.conf;
	include /etc/kvmd/nginx/loc-login.conf;
	include /etc/kvmd/nginx/loc-nocache.conf;
}
